```
 kubectl create secret generic ssh-secret  --type='kubernetes.io/ssh-auth'  --from-file=ssh-privatekey=/root/.ssh/id_rsa  --from-file=ssh-publickey=/root/.ssh/id_rsa.pub --from-file=known_hosts=/root/.ssh/known_hosts --dry-run=client -o yaml > secret.yaml
```

apiVersion: v1
data:
  known_hosts: fDF8WEhZRoREJ...
  ssh-privatekey: LS0tLS1CRUd..
  ssh-publickey: c3NoLXJ...
kind: Secret
metadata:
  name: ssh-secret
  annotations:
    tekton.dev/git-0: gitlab.done.com
type: kubernetes.io/ssh-auth
