stages:
  - build-pkg
  - build-and-push_image
  - deploy
  
variables:
  image_url: harbor.done.com/project01/spring-boot-helloworld
  image_version: v1.1 
  CACHE_DIR: target/

cache:
  paths:
    - $CACHE_DIR

build-pkg:
  stage: build-pkg
  script:
    - mvn clean install
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day

build-and-push_image:
  stage: build-and-push_image
  before_script:
    - docker info
    - export build_time=$(date +%Y%m%d-%H%M%S)
  script:
    - docker login harbor.done.com # /home/gitlab-runner/.docker/config.json
    - docker build -t ${image_url}:${build_time}-${image_version} .
    - docker push  ${image_url}:${build_time}-${image_version}
  only:
    - main

deploy:
  stage: deploy
  script:
    - argocd  login argocd.done.com:32267  --insecure  --username admin  --password rLYs5B0iMhIzcOxL
    - argocd app get x1 --refresh
    - argocd  app  sync x1
  when: manual
